global using MorseCode.ITask;
global using System;
global using System.Threading.Tasks;
global using LionFire.Structures;
global using Microsoft.Extensions.Logging;
global using System.Collections.Generic;
global using System.Diagnostics;
global using System.Threading;
global using DynamicData;
